import { useState } from 'react'

const API = 'http://localhost:8000'

const SECTIONS = [
  { num:'01', label:'Verdict Summary',        desc:'Single clear conclusion with confidence level' },
  { num:'02', label:'Evidence Breakdown',     desc:'Per-model analysis weighted by reliability' },
  { num:'03', label:'Confidence Analysis',    desc:'P(Real) vs P(AI) spread interpretation' },
  { num:'04', label:'Feature Detection',      desc:'Visual artifacts driving the classification' },
  { num:'05', label:'Reliability Assessment', desc:'How much to trust this verdict' },
  { num:'06', label:"Devil's Advocate",       desc:'Strongest case for the opposing verdict' },
]

export default function ForensicTab({ result, file }) {
  const [apiKey, setApiKey]   = useState('')
  const [devil, setDevil]     = useState(true)
  const [report, setReport]   = useState('')
  const [loading, setLoading] = useState(false)
  const [done, setDone]       = useState(false)
  const [showKey, setShowKey] = useState(false)

  const generate = async () => {
    if (!apiKey.trim()) { alert('An Anthropic API key is required.'); return }
    if (!file) { alert('No image available. Upload an image first.'); return }
    setLoading(true); setReport(''); setDone(false)
    try {
      const fd = new FormData(); fd.append('file', file)
      const res = await fetch(
        `${API}/report?devil_advocate=${devil}&api_key=${encodeURIComponent(apiKey)}`,
        { method: 'POST', body: fd }
      )
      if (!res.ok) throw new Error(await res.text())
      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let text = ''
      while (true) {
        const { done: d, value } = await reader.read(); if (d) break
        text += decoder.decode(value, { stream: true }); setReport(text)
      }
      setDone(true)
    } catch (e) { setReport(`Error: ${e.message}`) }
    finally { setLoading(false) }
  }

  const download = () => {
    const blob = new Blob([
      `AI FORENSIC ANALYSIS REPORT\nTeam Wisconsin — MS Data Science Capstone 2026\n${'='.repeat(60)}\n\n${report}\n\nGenerated by Claude claude-sonnet-4-5`
    ], { type: 'text/plain' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = 'forensic_report.txt'
    a.click()
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>

      {/* ── What this does ── */}
      <div style={{
        borderRadius: 16, padding: '32px 36px',
        background: '#F5F1EE',
        border: '1px solid #E0D9D4',
        position: 'relative', overflow: 'hidden',
      }}>
        <div style={{ position: 'relative' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
            <div style={{
              width: 40, height: 40, borderRadius: 10,
              background: '#ffffff', border: '1px solid #E0D9D4',
              display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
            }}>
              <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                <circle cx="10" cy="10" r="8" stroke="#8C1D40" strokeWidth="1.5"/>
                <path d="M6 10.5L8.5 13L14 7" stroke="#8C1D40" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </div>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <h2 style={{ fontSize: 18, fontWeight: 700, color: '#1a1a1a', letterSpacing: '-0.02em', margin: 0 }}>
                  AI-Assisted Forensic Analysis
                </h2>
                <span style={{
                  display: 'inline-block', padding: '2px 9px', borderRadius: 4,
                  fontSize: 10, fontWeight: 700, fontFamily: 'JetBrains Mono, monospace',
                  letterSpacing: '0.1em', textTransform: 'uppercase',
                  background: '#EEEDFE', color: '#3C3489',
                }}>
                  XAI Layer
                </span>
              </div>
              <p style={{ fontSize: 11, color: '#888780', margin: '4px 0 0', fontFamily: 'JetBrains Mono, monospace' }}>
                Powered by Claude claude-sonnet-4-5 — Anthropic
              </p>
            </div>
          </div>

          <p style={{ fontSize: 14, color: '#5F5E5A', lineHeight: 1.75, maxWidth: '52rem', marginBottom: 22 }}>
            Claude interprets the full ensemble evidence — per-model predictions, confidence distributions,
            probability spreads, and agreement patterns — to produce a structured forensic report.
            This constitutes an <strong style={{ color: '#1a1a1a' }}>explainability layer</strong> that
            translates numerical outputs into expert-level reasoning.
          </p>

          {/* Sections preview */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 8 }}>
            {SECTIONS.filter((s,i) => devil || i < 5).map((s,i) => (
              <div key={i} style={{
                padding: '10px 14px', borderRadius: 8,
                background: '#ffffff', border: '1px solid #E0D9D4',
                display: 'flex', alignItems: 'flex-start', gap: 10,
              }}>
                <span className="mono" style={{ fontSize: 10, color: '#8C1D40', fontWeight: 700, flexShrink: 0, marginTop: 1 }}>{s.num}</span>
                <div>
                  <div style={{ fontSize: 11, fontWeight: 700, color: '#2a2a2a', marginBottom: 2 }}>{s.label}</div>
                  <div style={{ fontSize: 10, color: '#888780', lineHeight: 1.4 }}>{s.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── Config card ── */}
      <div style={{ borderRadius: 14, padding: '28px 30px', background: '#ffffff', border: '1px solid #E0D9D4' }}>
        <div className="mono" style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: '#888780', marginBottom: 20 }}>
          Report Configuration
        </div>

        {/* API Key */}
        <div style={{ marginBottom: 18 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
            <div className="mono" style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#5F5E5A' }}>
              Anthropic API Key
            </div>
            <a href="https://console.anthropic.com" target="_blank" rel="noreferrer"
              style={{ fontSize: 10, fontFamily: 'JetBrains Mono, monospace', color: '#8C1D40', textDecoration: 'none' }}>
              console.anthropic.com →
            </a>
          </div>
          <div style={{ position: 'relative' }}>
            <input
              type={showKey ? 'text' : 'password'}
              value={apiKey}
              onChange={e => setApiKey(e.target.value)}
              placeholder="sk-ant-api03-..."
              style={{
                width: '100%', padding: '11px 60px 11px 14px',
                background: '#FAFAF9', border: '1px solid #E0D9D4',
                borderRadius: 9, fontSize: 13,
                fontFamily: 'JetBrains Mono, monospace',
                color: '#1a1a1a', outline: 'none',
                boxSizing: 'border-box',
                transition: 'border-color 0.2s ease',
              }}
              onFocus={e => e.target.style.borderColor = '#8C1D40'}
              onBlur={e => e.target.style.borderColor = '#E0D9D4'}
            />
            <button onClick={() => setShowKey(!showKey)} style={{
              position: 'absolute', right: 12, top: '50%', transform: 'translateY(-50%)',
              background: 'none', border: 'none', cursor: 'pointer',
              fontSize: 10, fontFamily: 'JetBrains Mono, monospace', color: '#888780',
            }}>
              {showKey ? 'HIDE' : 'SHOW'}
            </button>
          </div>
          <p className="mono" style={{ fontSize: 10, color: '#B4B2A9', marginTop: 5 }}>
            Keys are not stored, logged, or transmitted beyond this inference request.
          </p>
        </div>

        {/* Devil's advocate toggle */}
        <div style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '14px 16px', borderRadius: 10, marginBottom: 22,
          background: '#F5F1EE', border: '1px solid #E0D9D4',
        }}>
          <div>
            <div style={{ fontSize: 13, fontWeight: 600, color: '#1a1a1a', marginBottom: 3 }}>
              Include Devil's Advocate Analysis
            </div>
            <div style={{ fontSize: 11, color: '#888780', maxWidth: '32rem' }}>
              Claude constructs the strongest case for the opposing verdict — surfaces model uncertainty and potential failure modes
            </div>
          </div>
          <button onClick={() => setDevil(!devil)} style={{
            width: 44, height: 24, borderRadius: 12, border: 'none', cursor: 'pointer',
            flexShrink: 0, marginLeft: 16,
            background: devil ? '#8C1D40' : '#D4B8BE',
            position: 'relative', transition: 'background 0.2s ease',
          }}>
            <div style={{
              position: 'absolute', top: 3, width: 18, height: 18, borderRadius: '50%',
              background: '#fff', transition: 'left 0.2s ease',
              left: devil ? 23 : 3,
              boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
            }} />
          </button>
        </div>

        {/* Generate button */}
        <button
          onClick={generate}
          disabled={loading}
          style={{
            width: '100%', padding: '14px', borderRadius: 10,
            border: 'none',
            background: loading ? '#F0EBE8' : '#8C1D40',
            color: loading ? '#B4B2A9' : '#ffffff',
            fontSize: 14, fontWeight: 700,
            fontFamily: 'JetBrains Mono, monospace',
            letterSpacing: '0.06em', textTransform: 'uppercase',
            cursor: loading ? 'not-allowed' : 'pointer',
            transition: 'all 0.2s ease',
          }}
          onMouseEnter={e => { if (!loading) e.currentTarget.style.background = '#7a1838' }}
          onMouseLeave={e => { if (!loading) e.currentTarget.style.background = '#8C1D40' }}
        >
          {loading ? (
            <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10 }}>
              {[0,1,2].map(i => (
                <span key={i} className="pulse-dot" style={{
                  width: 5, height: 5, borderRadius: '50%',
                  background: '#8C1D40', display: 'inline-block',
                  animationDelay: `${i * 0.2}s`,
                }}/>
              ))}
              Generating forensic analysis...
            </span>
          ) : (
            <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
              <svg width="15" height="15" viewBox="0 0 15 15" fill="none">
                <path d="M7.5 1L9.5 5.5H14L10.5 8.5L12 13.5L7.5 10.5L3 13.5L4.5 8.5L1 5.5H5.5L7.5 1Z" stroke="white" strokeWidth="1.2" strokeLinejoin="round"/>
              </svg>
              Generate Forensic Report
            </span>
          )}
        </button>
      </div>

      {/* ── Report output ── */}
      {report && (
        <div className="fade-in" style={{ borderRadius: 14, overflow: 'hidden', border: '1px solid #E0D9D4' }}>
          {/* Header */}
          <div style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '14px 24px', background: '#F5F1EE',
            borderBottom: '1px solid #E0D9D4',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <div style={{ width: 7, height: 7, borderRadius: '50%', background: '#8C1D40' }} className="pulse-dot" />
              <span style={{ fontSize: 10, fontWeight: 700, fontFamily: 'JetBrains Mono, monospace', letterSpacing: '0.1em', textTransform: 'uppercase', padding: '2px 9px', borderRadius: 4, background: '#F4C0D1', color: '#72243E' }}>
                Forensic Analysis
              </span>
              <span style={{ fontSize: 11, color: '#888780', fontFamily: 'JetBrains Mono, monospace' }}>
                AI Image Detection — Expert Report
              </span>
            </div>
            {done && (
              <button onClick={download} style={{
                fontSize: 11, fontFamily: 'JetBrains Mono, monospace',
                color: '#8C1D40', background: '#ffffff',
                border: '1px solid #E0D9D4', borderRadius: 7,
                padding: '5px 12px', cursor: 'pointer',
                transition: 'background 0.2s ease',
              }}
              onMouseEnter={e => e.currentTarget.style.background = '#FBF2F4'}
              onMouseLeave={e => e.currentTarget.style.background = '#ffffff'}
              >
                Export .txt
              </button>
            )}
          </div>

          {/* Body */}
          <div style={{ padding: '28px 32px', background: '#ffffff' }}>
            <div className="report-text" style={{ fontSize: 14, color: '#2a2a2a', lineHeight: 1.9 }}>
              {report}
            </div>
            {loading && (
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 16 }}>
                {[0,1,2].map(i => (
                  <div key={i} className="pulse-dot" style={{
                    width: 5, height: 5, borderRadius: '50%',
                    background: '#8C1D40', animationDelay: `${i * 0.2}s`,
                  }}/>
                ))}
                <span className="mono" style={{ fontSize: 11, color: '#888780' }}>Streaming analysis...</span>
              </div>
            )}
          </div>

          {/* Footer */}
          {done && (
            <div style={{
              padding: '11px 24px', borderTop: '1px solid #F0EBE8',
              background: '#F5F1EE',
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            }}>
              <span className="mono" style={{ fontSize: 10, color: '#B4B2A9' }}>
                Generated by Claude claude-sonnet-4-5 · Team Wisconsin · MS Data Science Capstone 2026
              </span>
              <span className="mono" style={{ fontSize: 10, color: '#8C1D40' }}>
                Anthropic XAI Layer
              </span>
            </div>
          )}
        </div>
      )}
    </div>
  )
}